version: "3"
services:
  server:
    image: node:10.16-alpine
    restart: always
    volumes:
      - ./build:/build
      - ./public:/public
    command: "node /build/server.js"
    ports:
      - "3000:3000"
