version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - add_ssh_keys:
            fingerprints:
              - "23:5c:b7:18:6e:ae:32:d9:dc:41:0b:d7:59:5e:50:40"
      - run: tar -cf build.tar build public
      - run: yes | scp -P $SSH_PORT build.tar $SSH_USER@$SSH_HOST:~/endpoint.uz/endpointsite/
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd endpoint.uz/endpointsite && tar -xf build.tar && git pull --rebase origin master && docker-compose down --rmi local && docker-compose up -d"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build


